maintainer: Dhanoop Karunakaran
debug: False
sql_alchemy:
  loc: '/app/instance'
  db: 'data.db'
type: 
  - 'Token'
  - 'Troubleshoot'
  - 'Information'
  - 'Other'
trim:
  name: 15
  content: 100
  extra: 7
email:
  smtp_server: 'smtp.gmail.com'
  smtp_port: 587
  notification_days: 10  # Start notifications when X days remain
  max_notifications: 3   # Maximum number of notifications per token
  trigger_hour: 13 # hour
  trigger_minute: 03 # minute
  timezone: 'Australia/Sydney'
  scheduled_time: '10:00 AM AEST'  # For displaying scheduled time and should be aligned with tigger_hour, trigger_minute and timezone
  