maintainer: Dhanoop Karunakaran
debug: False
sql_alchemy:
  loc: '/app/instance'
  db: 'data.db'
type: 
  - 'Token'
  - 'Troubleshoot'
  - 'Information'
  - 'Other'

trim:
  name: 10
  used_for: 30