maintainer: Dhanoop Karunakaran
debug: False
sql_alchemy:
  loc: '/app/instance'
  db: 'data.db'
type: 
  - 'token'
  - 'issue'
  - 'document'
  - 'other'

trim:
  name: 10
  used_for: 30