# Updating this table will not update the config database. 
# This file is to make sure whenever we install this system first time,
# config will be copied from here. Also, reset to default will set the value in the
# config table from here.
maintainer: Dhanoop Karunakaran
debug: False
sql_alchemy:
  loc: 
    value: '/app/db'
    edit: False  # Not editable - system path
  db: 
    value: 'data.db'
    edit: True   # Editable
type: 
  value: ['Token', 'Troubleshoot', 'Information', 'Other'] # These are the default types and project level types overrides it.
  edit: True   # Editable - manage artifact types through settings
  project_settings: True
default_type: 
  project_settings: True
  value: 'Token'
  edit: True   # Editable
general:
trim:
  name: 
    value: 15
    edit: True   # Editable
  content: 
    value: 100
    edit: True   # Editable
  extra: 
    value: 7
    edit: True   # Editable
email:
  smtp_server: 
    value: 'smtp.gmail.com'
    edit: False  # Not editable - system configuration
  smtp_port: 
    value: 587
    edit: True   # Editable
  notification_days: 
    value: 10    # Start notifications when X days remain
    edit: True   # Editable
  max_notifications: 
    value: 3     # Maximum number of notifications per token
    edit: True   # Editable
  notification_interval: 
    value: 24    # Hours between notifications
    edit: True   # Editable
  timezone: 
    value: 'Australia/Sydney'
    edit: True   # Editable
storage:
  image_path: 
    value: "static/uploads"  # Relative to app root
    edit: False  # Not editable - system path
  allowed_extensions: 
    value: ["jpg", "jpeg", "png", "gif"]
    edit: True   # Editable
  max_file_size: 
    value: 5242880  # 5MB in bytes
    edit: True   # Editable
  cleanup_threshold_hours: 
    value: 3     # Delete files older than the threshold
    edit: True   # Editable
backup:
  enabled: 
    value: True  # Enable weekly backups
    edit: True   # Editable
  backup_path: 
    value: "/app/backups"  # Where to store backup files
    edit: False  # Not editable - system path
  keep_backups: 
    value: 4     # Number of backup files to keep (4 weeks)
    edit: True   # Editable
  backup_database: 
    value: True  # Backup the SQLite database
    edit: True   # Editable
  backup_images: 
    value: True  # Backup uploaded images (can be large)
    edit: True   # Editable
  backup_day: 
    value: "monday"  # Day of week to run backup (monday, tuesday, etc.)
    edit: True   # Editable
exclude_display_pages_tools: 
    value: 
      - add_artifact
      - update_artifact
      - artifact_detail
      - projects
    edit: True   # Editable
tools: 
  project_settings: True
  # json_to_csv: 
  #   value: False  # Disabled on the project settings page by default. Always set as False
  #   edit: True   # Editable
  #   display_name: "JSON to CSV"
  #   description: "JSON to CSV conversion"
  #   icon: "fas fa-file-code"
  #   url: "/tools/json_to_csv"
  csv_to_json: 
    value: False  # Disabled on the project settings page by default. Always set as False
    edit: True   # Editable
    display_name: "CSV to JSON"
    description: "CSV to JSON conversion"
    icon: "fas fa-file-csv"
    url: "http://localhost:3333/extensions/csv_to_json" # csv_to_json should be match with above and the nodejs url
  nedav2_to_echosolv: 
    value: False  # Disabled on the project settings page by default. Always set as False
    edit: True   # Editable
    display_name: "Neda V2 CSV to EchoSolv JSON"
    description: "Nedav2 CSV to echosolv json conversion"
    icon: "fas fa-file-csv"
    url: "http://localhost:3333/extensions/nedav2_to_echosolv" # nedav2_to_echosolv should be match with above and the nodejs url
