maintainer: Dhanoop Karunakaran
debug: False
sql_alchemy:
  loc: '/app/db'
  db: 'data.db'
type: 
  - 'Token'
  - 'Troubleshoot'
  - 'Information'
  - 'Other'
trim:
  name: 15
  content: 100
  extra: 7
email:
  email:
  smtp_server: 'smtp.gmail.com'
  smtp_port: 587
  notification_days: 10  # Start notifications when X days remain
  max_notifications: 3   # Maximum number of notifications per token
  notification_interval: 1  # Hours between notifications
  timezone: 'Australia/Sydney'
storage:
  image_path: "static/uploads"  # Relative to app root
  allowed_extensions: ["jpg", "jpeg", "png", "gif"]
  max_file_size: 5242880  # 5MB in bytes