maintainer: Dhanoop Karunakaran
debug: False
sql_alchemy:
  edit: True # It add this section to the config table and settings UI.
  loc: '/app/db'
  db: 'data.db'
type: 
  - 'Token'
  - 'Troubleshoot'
  - 'Information'
  - 'Other'
general:
  edit: True # It add this section to the config table and settings UI.
  default_type: 'Token'
trim:
  edit: True # It add this section to the config table and settings UI.
  name: 15
  content: 100
  extra: 7
email:
  edit: True # It add this section to the config table and settings UI.
  smtp_server: 'smtp.gmail.com'
  smtp_port: 587
  notification_days: 10  # Start notifications when X days remain
  max_notifications: 3   # Maximum number of notifications per token
  notification_interval: 24  # Hours between notifications
  timezone: 'Australia/Sydney'
storage:
  edit: True # It add this section to the config table and settings UI.
  image_path: "static/uploads"  # Relative to app root
  allowed_extensions: ["jpg", "jpeg", "png", "gif"]
  max_file_size: 5242880  # 5MB in bytes
  cleanup_threshold_hours: 3  # Delete files older than the threshold