# Updating this table will not update the config database. 
# This file is to make sure whenever we install this system first time,
# config will be copied from here. Also, reset to default will set the value in the
# config table from here.
maintainer: Dhanoop Karunakaran
debug: False
sql_alchemy:
  loc: 
    value: '/app/db'
    edit: False  # Not editable - system path
  db: 
    value: 'data.db'
    edit: True   # Editable
type: 
  value: ['Token', 'Troubleshoot', 'Information', 'Other'] # These are the default types and project level types overrides it.
  edit: True   # Editable - manage artifact types through settings
  project_settings: True
default_type: 
  project_settings: True
  value: 'Token'
  edit: True   # Editable
general:
trim:
  name: 
    value: 15
    edit: True   # Editable
  content: 
    value: 100
    edit: True   # Editable
  extra: 
    value: 7
    edit: True   # Editable
email:
  smtp_server: 
    value: 'smtp.gmail.com'
    edit: False  # Not editable - system configuration
  smtp_port: 
    value: 587
    edit: True   # Editable
  notification_days: 
    value: 10    # Start notifications when X days remain
    edit: True   # Editable
  max_notifications: 
    value: 3     # Maximum number of notifications per token
    edit: True   # Editable
  notification_interval: 
    value: 24    # Hours between notifications
    edit: True   # Editable
  timezone: 
    value: 'Australia/Sydney'
    edit: True   # Editable
storage:
  image_path: 
    value: "static/uploads"  # Relative to app root
    edit: False  # Not editable - system path
  allowed_extensions: 
    value: ["jpg", "jpeg", "png", "gif"]
    edit: True   # Editable
  max_file_size: 
    value: 5242880  # 5MB in bytes
    edit: True   # Editable
  cleanup_threshold_hours: 
    value: 3     # Delete files older than the threshold
    edit: True   # Editable
backup:
  enabled: 
    value: True  # Enable weekly backups
    edit: True   # Editable
  backup_path: 
    value: "/app/backups"  # Where to store backup files
    edit: False  # Not editable - system path
  keep_backups: 
    value: 4     # Number of backup files to keep (4 weeks)
    edit: True   # Editable
  backup_database: 
    value: True  # Backup the SQLite database
    edit: True   # Editable
  backup_images: 
    value: True  # Backup uploaded images (can be large)
    edit: True   # Editable
  backup_day: 
    value: "monday"  # Day of week to run backup (monday, tuesday, etc.)
    edit: True   # Editable