version: '3.8'

services:
  keepstone:
    build: .
    ports:
      - "2222:2222"
    volumes:
      - ./:/app
      - ./logs:/var/log/keepstone
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped